name: CI workflow

on:
  push:

jobs:
  build: # Job name
      runs-on: ubuntu-latest # Github Runner (Free)
      steps:
        - name: Checkout code # Step name
          uses: actions/checkout@v4 # Clone the code into a ubunty runner

        - name: Setup Docker
          uses: docker/setup-buildx-action@v4
